name: npm test and publish

on:
  push:
    branches:
      - master
      - main
    paths:
      - "src/*"
      - "package*"
  pull_request:
  workflow_dispatch:

jobs:
  main:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: test
        run: |
          npm ci
          npm test
      - name: build
        run: |
          npm run build
      - name: "version bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: publish
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
